# Generated by Django 4.0.4 on 2022-07-18 02:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(verbose_name='wins')),
                ('loss', models.IntegerField(verbose_name='loss')),
                ('points', models.IntegerField(verbose_name='points')),
                ('day_played', models.DateField(default=datetime.datetime.today, verbose_name='date')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.player', verbose_name='player')),
            ],
        ),
    ]
