# Generated by Django 4.0.4 on 2022-07-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_game_wins_alter_game_loss_alter_game_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='played',
            field=models.IntegerField(default=0, verbose_name='played'),
        ),
    ]
