# Generated by Django 4.0.4 on 2022-07-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_game_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.CharField(max_length=255, verbose_name='player'),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
