# Generated by Django 4.0.4 on 2022-07-20 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_alter_game_player_delete_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='day_played',
            field=models.DateField(default=datetime.date(2022, 7, 20)),
        ),
    ]
